import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import BottomBar from "./components/BottomBar";
import StickyCursor from "./components/StickyCursor";
import LoadingScreen from "./components/LoadingScreen"; // Added import for LoadingScreen

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const offBitFont = localFont({
  src: "../../public/fonts/OffBitTrial-DotBold.otf",
  variable: "--font-offbit",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Google Fonts Preconnect and Import */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Fleur+De+Leah&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${offBitFont.variable} antialiased`}
      >
        <LoadingScreen /> {/* Added LoadingScreen component */}
        <StickyCursor />
        <Navbar />
        <main className="relative min-h-screen bg-[#F8F5F0]">
          <div className="absolute inset-0 grid grid-cols-3 pointer-events-none z-0">
            <div className="border-r border-gray-300"></div>
            <div className="border-r border-gray-300"></div>
            <div></div>
          </div>
          <div className="relative z-10">
            {children}
          </div>
        </main>
        <BottomBar />
      </body>
    </html>
  );
}
